# Generated by Django 5.2 on 2025-04-23 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('pc', 'كمبيوتر'), ('laptop', 'لابتوب'), ('switch', 'سويتش'), ('access_point', 'Access Point'), ('router', 'راوتر'), ('projector', 'بروجكتر'), ('interactive_screen', 'شاشة تفاعلية'), ('na', 'N/A')], max_length=50)),
                ('device_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('operating_system', models.CharField(choices=[('win7', 'Windows 7'), ('win10', 'Windows 10'), ('win11', 'Windows 11'), ('android', 'Android'), ('na', 'N/A')], max_length=20)),
                ('status', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('weak', 'ضعيف')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
