# Generated by Django 5.2 on 2025-04-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('schools', '0002_rename_school_image_school_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_name',
        ),
        migrations.AlterField(
            model_name='device',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Projector', 'Projector'), ('Switch', 'Switch'), ('Router', 'Router'), ('Access Point', 'Access Point'), ('Screen', 'Interactive Screen'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.CharField(choices=[('Windows 7', 'Windows 7'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Android', 'Android'), ('NA', 'N/A')], max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Excellent', 'ممتاز'), ('Good', 'جيد'), ('Poor', 'ضعيف')], max_length=30),
        ),
    ]
