# Generated by Django 5.2 on 2025-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Makkah', 'Makkah'), ('Madinah', 'Madinah'), ('Eastern', 'Eastern Province'), ('Qassim', 'Qassim'), ('Asir', 'Asir'), ('Tabuk', 'Tabuk'), ('Hail', 'Hail'), ('Northern', 'Northern Borders'), ('Jazan', 'Jazan'), ('Najran', 'Najran'), ('Bahah', 'Al Bahah'), ('Jawf', 'Al Jawf')], max_length=50),
        ),
    ]
