# Generated by Django 5.2 on 2025-04-23 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location_gps', models.CharField(max_length=255)),
                ('school_image', models.ImageField(blank=True, null=True, upload_to='school_images/')),
                ('classrooms', models.IntegerField(blank=True, null=True)),
                ('pc_need', models.IntegerField(blank=True, null=True)),
                ('projector_need', models.IntegerField(blank=True, null=True)),
                ('labs_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
