# Generated by Django 5.2 on 2025-04-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='location_gps',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='school',
            name='pc_need',
        ),
        migrations.RemoveField(
            model_name='school',
            name='projector_need',
        ),
        migrations.AddField(
            model_name='school',
            name='classes_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='laptop_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='pc_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='projector_needed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='labs_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
