# Generated by Django 5.2 on 2025-04-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_school_image_school_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Makkah', 'Makkah'), ('Madinah', 'Madinah'), ('Eastern', 'Eastern Province'), ('Qassim', 'Qassim'), ('Asir', 'Asir'), ('Tabuk', 'Tabuk'), ('Hail', 'Hail'), ('Northern', 'Northern Borders'), ('Jazan', 'Jazan'), ('Najran', 'Najran'), ('Bahah', 'Al Bahah'), ('Jawf', 'Al Jawf')], default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
