# Generated by Django 5.2 on 2025-04-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(max_length=50),
        ),
    ]
